open-truss/open-truss

packages/open-truss/.github/workflows/publish-package.yml
We should set up a process for the open-truss npm pacakge
For now while we are still scaffolding the app and not too worried about breaking changes, I setup an action that publishes everytime a push to main happens (in other words a PR is merged). Eventually we probably want to revisit this process and have something more methodical like linking publishes to GitHub releases. i.e. everything we make a new release we can automatically publish the package.
Alternative options are:
- Move forward with the release approach and publish packages everything a release is made. This felt a little too heavy handed in these early days
- Have people manually publish to npm from their local env. This is probably fine, but having some automation reduce the friction here felt nice.
@open-truss/engineers
=> Publish package on every merge for now

.github/workflows/publish-package.yml, packages/open-truss/package.json
Fixes the script that publishes a new package every time a PR merges. Can see the package successfully publish in this actions run https://github.com/open-truss/open-truss/actions/runs/6738603968/job/18318529441
One quirk that I'm not realizing is that we'll need to bump the package version on every PR. A couple thoughts:
- We could add a CI step that fails the build if the PR has a package version lower than what is on main. That will remind us to bump the version.
- If bumping the package version every time we open a PR sounds tedious, perhaps we should abandon this approach altogether. We can disable this actions job and rely on publishing packages manually for now. Eventually when this is in a stable version we can trigger publishes when we open releases in GitHub. …
=> Fix package publishing

.github/workflows/ci-checks.yml, packages/open-truss/.eslintrc.js, packages/open-truss/package-lock.json, packages/open-truss/package.json
We want to have a linter build step generally. More importantly, it seems like at least one status check is required in order to require PRs be up to date before merging. To enable this, I went ahead and adding a linting status check.
> **Require branches to be up to date before merging**
> This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take effect unless at least one status check is enabled (see below).
This PR adds eslint to the project and runs it as a status check.
@open-truss/engineers
=> Add linter

.eslintignore, .eslintrc.js, demo-app/src/app/layout.tsx, demo-app/src/app/page.tsx, demo-app/src/app/workflows/[id]/Workflow.tsx, demo-app/src/app/workflows/[id]/page.tsx, demo-app/src/components/AvailableWorkflows.tsx, demo-app/src/display-components/PageTitle.tsx, demo-app/src/display-components/index.ts, package.json, packages/open-truss/src/hello_world/index.ts, packages/open-truss/src/index.ts, packages/open-truss/src/utils/format.ts, packages/open-truss/src/utils/yaml.ts, tsconfig.json
Building on and targeting #33 as the base to merge into this PR tries to apply the fixes suggested by the linter but also disables a few lint rules per our preferences.
Definitely open to feedback on whether the rules I disabled make sense to everyone and if there are any others we might want to enable or disable.
- `@typescript-eslint/comma-dangle`: https://typescript-eslint.io/rules/comma-dangle/
- `@typescript-eslint/space-before-function-paren`: https://typescript-eslint.io/rules/space-before-function-paren/
- `react/react-in-jsx-scope`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md
- `@typescript-eslint/return-await`: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md
- …
=> Tweak linting rules and apply fixes

config-spec.md
Everything in Open Truss is powered by configurations. Starting to iterate on what the configuration specification is early on could help us prototype features.
I started a `config-spec.md` document in the root of this repo. In it I define a few key concept and then illustrate them with a sample configuration.
[Here it is rendered](https://github.com/open-truss/open-truss/blob/config-spec-v0/config-spec.md).
In my opinion, stuff like this is really difficult to read typically. If folks have examples of projects that have significant configuration that document its use well, I'd love to see them so we can build off a good example.
- I said that everything has an ID but didn't expand on that at all.
- I have thoughts about query reuse that I'll post in a comment on this PR so we can discuss …
=> First draft of config spec

.github/workflows/publish-package.yml, packages/open-truss/.gitignore, packages/open-truss/bin/append-package-json-to-dist, packages/open-truss/bin/build, packages/open-truss/bin/tsc-watch, packages/open-truss/package.json, packages/open-truss/tsconfig.esm.json, packages/open-truss/tsconfig.json
resolves https://github.com/open-truss/open-truss/issues/31
@jonmagic and I found a great [blog post](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html) that gave instructions on how to organize a typescript project like OT in a sane way. We were already following some of the suggestions, but we should implement the rest
This PR implements the rest of the suggestions. Notably, it moves the output javascript files into `dist/cjs` and `dst/mjs` folders and adds `package.json` files to the dist folders. The easiest way to review this PR is commit by commit and reading the comments included, it should be pretty straightforward.
I tested these changes in the demo app and application we use at GitHub and everything worked as expected. 
@open-truss/engineers
=> Improve dev env

demo-app/script/server, packages/open-truss/bin/tsc-watch
It's kinda annoying to have to open two terminals to run the demo app and start tsc:watch.
This PR combines those two into one `script/server` command
@open-truss/engineers
=> Add script server for demo app

.prettierignore, demo-app/src/open-truss/components/Foo.tsx, packages/open-truss/nextjs/src/open-truss/components/Foo.tsx, packages/open-truss/src/components/OTBar.tsx, packages/open-truss/src/configuration/apply.tsx, packages/open-truss/src/configuration/engine-v1.tsx
To leverage React Server Components we need the ability to support async open truss components
This PR updates the type defs of our rendering engine so that it supports async open truss components. Some things of note:
- We ran into issues where calling `<Component key={i} data={data} config={config} {...props} />` would throw type errors because we updated the type to where Component could now also be a `Promise<JSX.Element>` in addition to `JSX.Element`. It took a while but I figured out the issue was `<Component />` was the incorrect way to call a promise. Instead this code just calls `Component` as a function instead of the syntactic sugar and `awaits` the promise.
- I dropped the usage of `React.FC<>`. After googling around I found that this is no longer the recommended way to …
=> Update rendering engine to support async components

demo-app/package-lock.json, demo-app/package.json, demo-app/src/app/api/graphql/route.ts
I would like to start demonstrating a non-Next.js way of using open-truss that leverages an apollo server backend for querying and mutating data.
My plan is to build on this PR and add a `uqiQuery` query to the graphql schema. The backend will use the uqi library and any clients we've created in the demo-app to retrieve and return (and/or maybe stream?) data to the client. Then I'll build a simple query UI where a user can submit a query and view the results.
I think this will get us closer to starting to use open-truss in a more meaningful way at the day job.
I followed these instructions: https://javascript.plainenglish.io/using-apollo-server-with-nextjs-13-app-dir-part-1-google-auth-with-nextauth-prisma-ca242c92599e
You can test out this PR by:
```
cd demo-app
npm install
script/server …
```
=> Add /api/graphql routes to demo-app to start using apollo server

demo-app/src/app/ot/playground/[slug]/page.tsx, demo-app/src/app/ot/rsc-playground/[slug]/page.tsx, demo-app/src/components/RenderFromEndpoint.tsx, demo-app/src/components/RenderFromFile.tsx
I noticed after merging #64 that the playground pages were upset with a type error because the `AsyncPageTitle` component doesn't adhere to OT's `BaseOpenTrussComponentV1` type, specifically that it is async and thus doesn't have a ReturnType of `JSX.Element` but instead of `Promise<JSX.Element>`.
Okay so maybe this is a smell, but I got around this by erasing the types of the imported components.
If we extend `BaseOpenTrussComponentV1` to return `JSX.Element | Promise<JSX.Element>`, then to make things happy we have to add an `async` to the engine, which breaks rendering client components.
I wonder if folks think this solution, erasing the types of the imported components, is unacceptable. If it is, perhaps now is the time to discuss dropping RSC or not.
I think there may be another …
=> Consolidate component getting and fix up types

packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/components/README.md, packages/open-truss/src/configuration/apply.tsx, packages/open-truss/src/configuration/engine-v1.tsx, packages/open-truss/src/utils/yaml.ts
I want to create a UX for building configs and to do that it will be helpful to inspect a component's props at runtime.
[`zod`](https://zod.dev/) is a popular runtime validation library that also has great TypeScript support. In this PR I've converted all our types to use `zod`. Well, almost all, Yaml is super recursive which is difficult, but I got it handled!
**NOTE:** I didn't bump the engine version as there are no breaking changes here. In fact, there are no changes at all! The exported types should be equivalent.
In a subsequent PR I'll show you how we can inspect zod's prop descriptions at runtime and build a UX on top of it. I've already validated this so I think this approach is worthwhile. I want to merge this sooner than I'll get to the next part since it's a pain to update …
=> Convert all types to zod

demo-app/package-lock.json, demo-app/package.json, demo-app/src/app/api/graphql/route.ts, demo-app/src/app/api/graphql/synchronous-uqi-query.ts, demo-app/src/app/api/synchronous-uqi-query/route.ts, demo-app/src/lib/trino-uqi-client.ts, demo-app/src/lib/uqi-sources.ts
I want to start working on react hooks for interacting with the unified query interface but first I need some backend endpoints to hit to execute synchronous uqi queries.
Review commit by commit.
```bash
cd demo-app
npm install
script/server
```
**Note:** Don't forget to start trino! See [these instructions](https://trino.io/docs/current/installation/containers.html#running-the-container)
Test the graphql endpoint by loading http://localhost:3000/api/graphql and executing this query:
```graphql
query Query($source: String!, $query: String!) {
synchronousUqiQuery(source: $source, query: $query) {
rows {
values {
key
type
value
}
}
metadata {
columns {
name
type
}
}
}
}
```
With these variables:
```json
{
"source": "trino-demo",
"query": "select * from  tpch.sf1.customer limit 10"
}
``` …
=> Add graphql query and REST endpoint for executing synchronous uqi query

packages/open-truss/src/configuration/engine-v1.tsx
I was getting console warnings about components not having unique keys. It turns out that calling the component as a function like this breaks that. Since we don't need to `await` these anymore, we can just construct JSX per usual.
Please notice my branch name :)
=> Fix issue where subframes weren't getting keys

packages/open-truss/src/components/index.ts, packages/open-truss/src/configuration/apply.tsx, packages/open-truss/src/configuration/engine-v1.tsx
While working on my config builder UX I noticed a few things could be improved.
- Add OT_COMPONENTS as an export of all OT components.
- engine-v1 supports components that have named exports.
- This is important as I want to introduce exporting a `Props` constant to inspect a component's prop types.
- Mark some optional props as optional.
- Throw an error when children aren't supported but are attempted to be used.
=> engine-v1: type improvements, handle named exports, catch misbehaving children

demo-app/package-lock.json, demo-app/package.json, demo-app/src/app/ot/config-builder/page.tsx, demo-app/src/components/RenderConfig.tsx, demo-app/src/components/RenderFromEndpoint.tsx, demo-app/src/components/RenderFromFile.tsx, demo-app/src/open-truss/components/ClientPageTitle.tsx, demo-app/src/open-truss/components/index.ts, demo-app/src/open-truss/configs/3-client-example.yaml
I think having a UX to build configs will help us get folks excited by OT, teach users how to write configs, and make it fun to create new configs.
My other recent PRs that have been building towards this:
- #69
- #70
- #75
- Refactor `RenderConfig` out of `RenderFrom{Endpoint,File}`.
- This lets the config builder render its in-memory config that it has built.
- Add `zod` to demo-app
- First draft of config builder UX
- Currently it only knows how to handle primitive types, but these start to show the possibilities.
- I updated `ClientPageTitle` to have some silly props to showcase what's possible.
- The UI is partying like it's 1989.
https://github.com/open-truss/open-truss/assets/3272924/bca0b8ce-abb6-4d51-9186-488df397ea1e
Next up is handling `children` so we can get sub-frames going …
=> First draft of config builder

demo-app/script/bootstrap
> Invalid Hook Call
> Hooks can only be called inside the body of a function component.
> There are three common reasons you might be seeing it:
> 1. You might have mismatching versions of React and React DOM.
> 2. You might be breaking the [Rules of Hooks](https://legacy.reactjs.org/docs/hooks-rules.html).
> 3. You might have more than one copy of React in the same app.
Read through https://iws.io/2022/invalid-hook-multiple-react-instances a few times and then updated `script/bootstrap` to create the correct link so the open-truss package is linked to the react version the demo-app is using.
=> Fix how @open-truss/open-truss package uses react

demo-app/package-lock.json, demo-app/src/open-truss/configs/2-available-workflows.yaml, demo-app/src/pages/ot/playground/index.tsx, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/configuration/engine-v1/Frame.tsx, packages/open-truss/src/configuration/engine-v1/config-schemas.tsx
This is an alternative solution to the `props[name].type`/`props[name].value` solution from https://github.com/open-truss/open-truss/pull/94: instead of saying that something has `type: component`, I am introducing a syntax way to specify it:
```diff
workflow:
version: 1
frames:
- frame:
view:
component: OTAvailableWorkflowsFromEndpoint
props:
link:
-           type: component
-           value: NextLink
+         link: <NextLink />
```
While more magical, I like that this removes the need to specify that every string is a string and number is a number; this could really add up to a lot of lines in large configs.
What do you all think?
=> Instead of saying what type a prop is, use <Component /> syntax

demo-app/src/pages/ot/playground/[slug]/index.tsx, packages/open-truss/src/configuration/RenderConfig.tsx, packages/open-truss/src/configuration/engine-v1/Frame.tsx, packages/open-truss/src/configuration/engine-v1/RenderConfig.tsx, packages/open-truss/src/pages/config-builder-page/index.tsx
Closes https://github.com/open-truss/open-truss/issues/103.
While building a config, having the page break totally when you misconfigure something is an unpleasant experience. I've taught `<Frame />` to catch errors related to failing to find a component and render a UI saying what's up:
This could be where we do other frame-level config validations, like prop validation.
=> Catch and display frame configuration errors

demo-app/src/open-truss/components/ClientPageTitle.tsx, demo-app/src/open-truss/components/NextLink.tsx, demo-app/src/open-truss/components/TrinoDemo.tsx, demo-app/src/open-truss/components/YourAppExampleComponent.tsx, packages/open-truss/src/components/OTAvailableWorkflowsFromEndpoint.tsx, packages/open-truss/src/components/OTExampleComponent.tsx, packages/open-truss/src/configuration/engine-v1/RenderConfig.tsx, packages/open-truss/src/configuration/engine-v1/config-schemas.tsx, packages/open-truss/src/configuration/engine-v1/index.ts, packages/open-truss/src/pages/config-builder-page/index.tsx
This PR does two main things:
1. `withChildren` is just an object now. The function way was throwing away types and after refactoring it to not do this I realized that I think this is more ergonomic.
2. `BaseOpenTrussComponentV1` is now a generic type that can be used to declare components. I think this is nice as we don't need to type every component as returning JSX.Element.
**Before**
**After**
=> Refactor types to make them more descriptive

demo-app/src/pages/ot/config-builder/PropInput.tsx
1. Not really sure how to fix the infinite render loop so I just made this change for now: 783245204e99b140a00d5c8d5c8fc6fc27c01dc5
2. These imports should come from open-truss and not the demo-app: cca6a9f32fdfeae738423f8a35546753889b4fc3
Still one outstanding bug afaict related to signals:
App go boom 💥
=> Fix render bug in config builder

demo-app/src/pages/ot/config-builder/index.tsx, packages/open-truss/src/configuration/RenderConfig.tsx, packages/open-truss/src/configuration/engine-v1/RenderConfig.tsx
@jonmagic pointed out that the config builder was having trouble accessing `localStorage`. The demo app is NextJS which always tries to server render things. `localStorage` isn't on the server so this broke the config builder, which is able to rendered on the server. This didn't affect config playground pages because the `RenderConfig` calls are done in the client just by the fact that we fetch the config on page load using an API.
This was because I was using `Object.assign` to merge the demo app's components with OT's components. `Object.assign` [mutates the target object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) which led to weird behavior. I fixed it by duplicating the object within the assign. I also fixed all cases of this even …
=> Two small fixes for the config builder

demo-app/package.json, demo-app/script/server, packages/open-truss/bin/tsc-watch
We're seeing some time related issues when running script/server that causes the editor and builds to throw errors sometimes but not all of the time.
Synchronously compile at the beginning of script/server before starting the asynchronous builds.
=> Add --sync option to packages/open-truss/bin/tsc-watch and use in script/server

demo-app/src/pages/ot/config-builder/ComponentList.tsx, demo-app/src/pages/ot/config-builder/ConfigYaml.tsx, demo-app/src/pages/ot/config-builder/PropInput.tsx, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/configuration/RenderConfig.tsx, packages/open-truss/src/configuration/engine-v1/Frame.tsx, packages/open-truss/src/configuration/engine-v1/RenderConfig.tsx, packages/open-truss/src/configuration/engine-v1/config-schemas.tsx, packages/open-truss/src/hooks/config-builder.tsx
Some consumers of OT use React 17. We should try and make this compatible with that.
React 18 has types that don't exist in React 17. This PR removes usage of those types where they are not necessary, while making this still work for React 18. e.g. changing `React.JSX.Element` -> `JSX.Element`. 
Additionally, this PR adds a missing `typings` declaration in the package.json config that supports targets that don't know how to use the `exports` annotation to find typedefs. e.g. `moduleResolution: node`.
While this PR resolves the conflicts for React 17, it does bring up a larger issue of how do we want to prevent breaking changes like this in the future or also do we even want to support React 17 long-term. Some ideas:
- As a general rule of thumb, we can try not using `React` types directly …
=> Make compatible with react 17

demo-app/src/open-truss/components/SimpleSignalExample.tsx, demo-app/src/pages/ot/playground/[slug]/index.tsx, demo-app/tsconfig.json
Resolves https://github.com/open-truss/open-truss/issues/143
Updated the state management demo page by styling the `SimpleSignalExample` and the `H1` in `playground/index`
Changes from this PR:
Found https://flowbite.com/docs/components/buttons/ and https://tailwindcss.com/docs/flex-direction to be helpful for styling
=> Add styling to `SimpleSignalExample`

packages/open-truss/package.json, packages/open-truss/src/hooks/config-builder.tsx, packages/open-truss/src/utils/yaml.test.ts, packages/open-truss/src/utils/yaml.ts
Because we ran into a situation where we wanted this and it did not support it.
**PLEASE NOTE** this does not actually do runtime type checking on the parsed version of the yaml string being parsed. If we want that we should incorporate zod into this function.
Co-authored-by @spicycode, @tmetz, @hktouw, @andrew-dillon, @fionaochs
=> Update parseYaml function to take optional generic type

packages/open-truss/package.json, packages/open-truss/src/utils/format.ts
Because it was bugging me that this wasn't the default 😬
=> Uppercase keywords be default in query formatter

demo-app/script/bootstrap, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/index.ts
I would like to have access to all of the public API from the `@preact/signals-react` library. I also need to switch between development on my work app and the demo-app easier. We already had things working on the work app but when switching back to the demo-app it wasn't fixing the npm link for react.
See commits.
=> Expose more of @preact/react-signals and make switching apps easier

demo-app/src/open-truss/configs/4-trino-demo.yaml, packages/open-truss/package.json, packages/open-truss/src/components/OTUqiDataProvider.tsx, packages/open-truss/src/configuration/engine-v1/Frame.tsx, packages/open-truss/src/configuration/engine-v1/RenderConfig.tsx, packages/open-truss/src/configuration/engine-v1/config-schemas.tsx
To make debugging easier in OT components, this PR extends the base OT component type with a `debug` prop. OT components can then opt into using that prop to output useful debugging results. Debugging is then enabled by setting `debug: true` at the top of the config file. Later, this may wanted to be set elsewhere, but this felt like the most sense for the time being.
You can see in this demo, debugging is added to the `OTUquiDataprovider` component.
https://github.com/open-truss/open-truss/assets/4481584/f52cf631-8b07-473d-ab6a-ca9c68a77eb0
/cc @open-truss/engineers
=> Add debug flag

.eslintignore, .prettierignore, demo-app/README.md, demo-app/codegen.yml, demo-app/package-lock.json, demo-app/package.json, demo-app/src/pages/api/[...graphql].ts, demo-app/src/types/context.ts, demo-app/src/types/generated-types.ts, demo-app/src/types/schema.graphql
I want to start working on https://github.com/open-truss/open-truss/issues/169 but first wanted to add a simple graphql API to the demo-app that supports query, mutation, and subscription and also uses codegen to generate types from the graphql SDL and examples.
I leveraged ChatGPT heavily but also referenced some docs when ChatGPT gave me old examples
- https://chat.openai.com/share/0228ac85-db19-4cf8-baff-3167c1315517
- https://github.com/dotansimha/graphql-code-generator/issues/1090
- https://the-guild.dev/graphql/yoga-server/docs/features/subscriptions
- https://chatgpt.com/c/c76cff32-af69-4875-8d4a-83bc201892b6
Run the server:
```bash
script/server
```
Open the graphiql UI: http://localhost:3000/api/graphql
Examples:
```graphql
query {
hello {
message
}
}
```
```graphql
mutation { …
```
=> Add graphql api to demo-app

demo-app/src/lib/mysql-uqi-client.ts
I'm using the mysql-uqi-client in the demo-app to power the stored queries primitive and when I tried to use the mysql JSON type got an error because that type wasn't included in the type mappings.
Added the missing type to the mysql-uqi-client type mappings.
=> Add JSON type to mysql type mappings

demo-app/src/lib/kusto-uqi-client.ts, demo-app/src/lib/mysql-uqi-client.ts, demo-app/src/lib/trino-uqi-client.ts, demo-app/src/lib/uqi-sources.ts
When executing a query it would be nice to be able to reference what query engine and engine version that the uqi client was meant to work with.
Right now I want this for https://github.com/open-truss/open-truss/issues/169 so I can add a referenced in the stored query to the engine that was being used.
Refactor and put the `engine` and `engine_version` directly on the create function for each client.
=> Set engine and engine version

demo-app/package-lock.json, demo-app/src/lib/trino-uqi-client.ts, demo-app/src/open-truss/configs/15-arrays-signals-from-query.yaml, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/signals/index.tsx, packages/open-truss/src/uqi/uqi.ts
We need signals to support array values because those are common return types and data structures in databases
```yaml
workflow:
version: 1
signals:
r1:
value: number[]
r2:
value: string[]
frames:
- frame:
view:
component: OTUqiDataProvider
props:
source: mysql-demo
query: >
SELECT JSON_ARRAY(1, NULL, 3) AS value
output: [:r1]
frames:
- frame:
view:
component: DataDemo
props:
results: :r1
- frame:
view:
component: OTUqiDataProvider
props:
source: mysql-demo
query: >
SELECT JSON_ARRAY('one', NULL, 'three') AS value
output: [:r2]
frames:
- frame:
view:
component: DataDemo
props:
results: :r2
```
This PR
- https://github.com/open-truss/open-truss/pull/183/commits/7cdf5873c3942c80a59ff1e06f48df411cc84f50 Updates the dynamic signals code to do lookups in the pre-existing list of signals. …
=> Improve support for Array signals

demo-app/package-lock.json, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/signals/index.tsx
This is kinda a silly one, but I think still good to do. We use `crypto-js` to perform SHA hashing on a signal object, which is used to give each signal a unique name based on its definition. This package [has a non-ASCII character in its source code](https://github.com/brix/crypto-js/blob/ac34a5a584337b33a2e567f50d96819a96ac44bf/src/ripemd160.js#L2), which is not allowed in my project's build 😅 
To keep this functionality, which I think we should, I imported and used a different package: [`object-hash`](https://github.com/puleos/object-hash). It does less than `crypto-js`, but that's fine as all we need is the hashing capabilities. (I didn't check, but I'd assume the bundle size decreased due to this change :tada:)
I used example 6-state-management-demo to ensure signals are still …
=> use object-hash instead of crypto-js for object hashing

demo-app/package-lock.json, demo-app/src/lib/mysql-uqi-client.ts, demo-app/src/lib/trino-uqi-client.ts, demo-app/src/open-truss/configs/9-kusto-demo.yaml, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/uqi/example/fake-client-uqi.test.ts, packages/open-truss/src/uqi/uqi.ts
🍐 with @jonmagic 
https://github.com/open-truss/open-truss/issues/190
This PR lays some groundwork for reporting the percentage of a query that has completed.  We'd like this to work with Kusto, Trino, and MySQL for Uqi, but haven't been able to find a good metric for Kusto or Trino.  However, this PR adds the `percentageComplete` field that can be used if the data is available.
This also does a quick bugfix for the Kusto demo config to make it valid YAML.
=> Report percentageComplete

packages/open-truss/package.json
This will get #202 and #203 out for any downstream consumers.
=> 0.25.0 -> 0.26.0, pulling in CVE fixes from #202 and #203

packages/open-truss/package.json
I couldn't pull in the new GraphQL data provider changes which I believe is due to the package version not being updated
Updated the version 🥱
=> Update package version to 0.29.0

demo-app/package-lock.json, packages/open-truss/package-lock.json, packages/open-truss/package.json, packages/open-truss/src/components/OTUqiDataProvider.tsx
The changes in https://github.com/open-truss/open-truss/pull/215/files#r1744560877 actually broke OTUqiDataProvider as the asynchronous calls were happening outside a useEffect hook. I returned it to the previous implementation which used `useSignalEffect`.
=> Fix OTUqiDataProvider
